using System.Text.Json.Serialization;

namespace tsync;


//only exists because the Graph SDK sucks for creating tasks
//it doesn't work reliably, and random 400 errors are absolutely impossible to properly diagnose.
//the exception that is thrown contains precisely 0 information from the servers other than the HTTP response code of... 400.
//at least let me read what the actual error message from the server is! Why make this so difficult?
//and the even more fun HTTPClient timeouts, when seemingly identical requests over Graph Explorer work nearly instant?
//yeah, idk either.

//no PlannerTask can not be reused, it contains fields that Graph doesn't know what to do with.
//why? idk, ask Microsoft. They made it. Using an automated tool of course... it really shows
//I hate shitty SDK developers. 

//I almost feel like I would've been better off writing everything from scratch instead of trying to use
//these crappy SDKs  for this project. First Manatee.Trello sucked
//now the Graph SDK absolutely sucks too.

//SDK developers! Don't make your damn implementations so "opaque" as to not understand what the heck they're doing!
//the features I am still using from it I may re-implement. I did it in another project! I can do it again!
//but I will definitely remember this for next time! It's easier to just write the damn REST calls myself
//then try to get your stupid SDK to do the right thing!
public struct TPlannerTask
{
    [JsonPropertyName("@odata.etag")]
    public String? etag { get; init; }
    public String planId { get; init; }
    public String bucketId { get; init; }    
    public String title { get; init; }
    public String? conversationThreadId { get; init; }
    public String? id { get; init; }
    //don't even get me started on this stupidity either
    public String? orderHint { get; init; }
    
    //...I'm pretty sure you have to post details as a separate request
    //Graph does not seem to like if you give it everything in one shot
    //idk though, maybe I'm just stupid. I don't care though. It's Microsoft's servers that need to process it, not mine.
    //Request away!
    [JsonIgnore]
    public TPlannerTaskDetails? details { get; init; }
    
}


public struct TPlannerTaskDetails
{
    [JsonPropertyName("@odata.etag")]
    public String? etag { get; init; }
    //why? why microsoft? Why is this a separate field in details and not part of the main task?
    public String? description { get; init; }
    public Dictionary<String, TPlannerTaskExternalReference>? references { get; init; }
    public Dictionary<String, TPlannerTaskCheckItem>? checklist { get; init; }
    
    
}

public struct TPlannerTaskExternalReference
{
    
    [JsonPropertyName("@odata.type")]
    public String odatatype => "#microsoft.graph.plannerExternalReference";

    public String alias { get; init; }

    public String type => "Other";
    
    public DateTimeOffset? lastModifiedDateTime { get; init; }
    
    //no, I am not going to support lastModifiedBy. I don't care.
}

//docs say that this should have a Guid generated by client
//but Microsoft's own impl just generates random ass numbers?
//I'm serious, here's a real response from Graph explorer on a checklistitem created from the web UI for planner!
//"checklist": {
//    "24544": {
//        "@odata.type": "#microsoft.graph.plannerChecklistItem",
//        "isChecked": false,
//        "title": "test 3",
//        "orderHint": "858496Xi",
//        "lastModifiedDateTime": "2024-01-15T22:55:50.8375149Z",
//        "lastModifiedBy": {
//            "user": {
//                "displayName": null,
//                "id": "a582e0a3-c5e2-483f-822f-0bce64bce193"
//            }
//        }
//    },
//see? 24544 is not a guid!
//lies I tell you!
//https://learn.microsoft.com/en-us/graph/api/resources/plannerchecklistitems?view=graph-rest-1.0
//..the interesting part though, the random ass numbers aren't even sequential! the first item is 99461!
public struct TPlannerTaskCheckItem
{
    [JsonPropertyName("@odata.type")]
    public String odatatype => "#microsoft.graph.plannerChecklistItem";
    
    public Boolean isChecked { get; init; }
    
    public String title { get; init; }
    
    public String? orderHint { get; init; }
    
    public DateTimeOffset? lastModifiedDateTime { get; init; }
    //again, I don't care about supporting lastModifiedBy
}